
<div style="margin: 10px auto; width: 300px;;">
    <table class='login'>
        <tr>
            <td width ="115">Tên Ðăng Nhập</td>
            <td><input class='inputstyle2' type='text' id='useradmin' name='usernameadmin'/></td>
        </tr>
        
        <tr>
            <td>Mật Khẩu</td>
            <td>
                <input class='inputstyle2' type='password' id='passadmin' name='passwordadmin'/>
            </td>
        </tr>
        
        <tr>
            <td>
                
            </td>
            <td>
                <input class='btLoginAdmin inputstyle2' onclick="LoginAdmin({useradmin:document.getElementById('useradmin').value, passadmin:document.getElementById('passadmin').value })" type='button' name='btnlogin' value='Ðang Nhập' />
            </td>
        </tr>
        <tr>
            <td colspan='2'><span class='loidangnhap'></span></td>
        </tr>
        
    </table>
</div>