<?php
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center><img  src='".APP_DOMAIN."/application/templates/giaodien_admin/images/chon page.jpg'/></center>";
	}
	else
	{
    $DieuLe = $this->dieule;
?>

<form action = "dieule/chinhsuadieule" method = "post" enctype="multipart/form-data">

    <textarea id="ckdieule" class="textareastyle" type="text" name="dieule"><?php echo $DieuLe; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>	
	var editor1 = CKEDITOR.replace( 'ckdieule' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;
</script>
<?php } ?>














