<?php 
$linkcomment = "http://chodatonline.com".$_SERVER["REQUEST_URI"];
?>
<div>
    <div class="share">
        <div style="width:200px;">            
            <!-- post len tuong   -->
			<?php
			$facebook = new Ishali_Facebook();
			$fb = $facebook->getFB();			
			$pageid = $_SESSION['pageid'];
			$pages = 	$fb->api('/'.$pageid);
			$pages_name = $pages['name'];
			$pages_link = $pages['link'];
			$pages_category = $pages['category'];
			$pages_about = $pages['about'];
			$link_post_face=$pages_link."?sk=app_". APP_ID;
			$messages = "Bình chọn cho ". $this->info->ten_thi_sinh . " nhé! ";
			/*
			$fb->api('/me/feed', 'post', array(
			  'message' => $messages,
			  'link' => $link_post_face,
			  'name' => $pages_name,
			  'caption' => $pages_category,
			  'description' => $pages_about,
		  ));
		  */
		
		
			?>	
			<a onclick="danglentuong()" >đăng lên tường </a>
            <!-- share thi sinh   -->
			<?php
			$link_post_img = APP_DOMAIN . '/public/images/fb-share-button.png';
			echo "<td align='right' class='post_facebook'>
			<a href='http://www.facebook.com/share.php?u=$link_post_face' id='facebook_wall' title='Share to Facebook' target='_blank' onclick='return vtlai_openbookmark(this);'><img width='65px' height='23px' src='$link_post_img'/></a></td>";	
		
			?>
            <!-- gui cho ban be   -->
			<?php
			$idfriend = '100002280840454';
			?>
			<div id="fb-root"></div>
			<a href='#' onclick="FacebookInviteFriends();">Invite Friends</a>
        </div>

        <div>
            <h3>
                <a TARGET = "_blank"  href="http://www.facebook.com/<?php echo $this->info->id_fb_thi_sinh; ?>">
                    <?php echo $this->info->id_fb_thi_sinh . ' - ' . $this->info->ten_thi_sinh; ?>
                </a>
            </h3>
            <div>
                <?php
                $images = json_decode($this->info->hinh_du_thi);
                $imageLink = APP_DOMAIN . '/public/images/' . $images[0];
                ?>
                <img src='<?php echo $imageLink; ?>'/>
            </div>

            <div><?php echo $this->info->gioi_thieu; ?></div>
            <div><?php echo $this->info->mo_ta_bai_thi; ?></div>

            <p><span id="votingcount"><?php echo $this->info->luot_binh_chon; ?></span> Bình chọn</p>

            <?php if ($this->page->like_binh_chon == 1) { 
				echo $_SESSION['haslike'];
				if($_SESSION['haslike'] == 1)
				{
				?>
				 <p><a id="voting" href="javascript:void(0);">Bình chọn</a></p>
				<?php				
				}else
				{
						$imagelike = APP_DOMAIN . '/public/images/nutlike.png';
					echo  " Vui lòng  nhấn nút like  <img src='$imagelike'/> ở góc phải trên để bình chọn";
				}
			?>
               
            <?php }else
				{
			?>
			 <p><a id="voting" href="javascript:void(0);">Bình chọn</a></p>
			<?php
			}
			?>
        </div>

        <div class="comment">
            <!-- comment   -->    
			  <?php if ($this->page->like_binh_chon == 1) { 
				
				if($_SESSION['haslike'] == 1)
				{
				//TODO: admin facebook comment
				?>
				<div class="fb-comments" data-href="<?php echo $linkcomment?>" data-width="470" data-num-posts="2"></div>
				<?php				
				}else
				{
						$imagelike = APP_DOMAIN . '/public/images/nutlike.png';
					echo  " Vui lòng  nhấn nút like  <img src='$imagelike'/> ở góc phải trên để bình luận";
				}
			?>
               
            <?php }else
				{
				//TODO: gan link page
			?>
			<div class="fb-comments" data-href="<?php echo $linkcomment?>" data-width="470" data-num-posts="2"></div>
			<?php
			}
			?>
        </div>


    </div>
</div>

<script>
    //Change these values to style your modal popup
    var align = 'center';									//Valid values; left, right, center
    var ptop = 100; 											//Use an integer (in pixels)
    var width = 0; 										//Use an integer (in pixels)
    var padding = 10;										//Use an integer (in pixels)
    var backgroundColor = '#FFFFFF'; 						//Use any hex code
    var source = ''; 								//Refer to any page on your server, external pages are not valid e.g. http://www.google.co.uk
    var borderColor = '#333333'; 							//Use any hex code
    var borderWeight = 4; 									//Use an integer (in pixels)
    var borderRadius = 5; 									//Use an integer (in pixels)
    var fadeOutTime = 300; 									//Use any integer, 0 = no fade
    var disableColor = '#666666'; 							//Use any hex code
    var disableOpacity = 40; 								//Valid range 0-100
    var loadingImage = 'lib/release-0.0.1/loading.gif';		//Use relative path from this page

    source = '<table style="text-align: center; width: 380px;"><tr><td>[content]</td></tr></table>';
    
    //This method initialises the modal popup
    		
        
    $("#voting").click(function(){		
        if(true){
            var data ={"id":"<?php echo $this->info->id_thi_sinh ?>"};
            $.ajax({
                type: "POST",
                url: "<?php echo APP_DOMAIN; ?>/index/voting",
                data: data,
                dataType: "json"
            }).done(function(data) { 
                if(data.errorCode>=0){		
                    var voting = parseInt($("#votingcount").html());
                    ++voting;
                    $("#votingcount").html(voting);                    
                    $('#voting').unbind('click');
                }
                var msg = source.replace('[content]', data.message);
                modalPopup(align, ptop, width, padding, disableColor, disableOpacity, backgroundColor, borderColor, borderWeight, borderRadius, fadeOutTime, msg, loadingImage);
            });
        }		
    });
</script>
    <script src="http://connect.facebook.net/en_US/all.js"></script>

	<script type="text/javascript">
   
	
	 function danglentuong() {
		FB.ui(
		  {
			method: 'feed',
			name: '<?php echo $pages_name ?>',
			link: '<?php echo $link_post_face ?>',
			caption: '<?php echo $pages_category ?>',
			 picture: 'http://fbrell.com/f8.jpg',
			message: '<?php echo $messages ?>',
			description: '<?php echo  $pages_about ?>'
		  },
		  function(response) {
			if (response && response.post_id) {
			  alert('Đã đăng lên tường');
			} 
		  }
		);
	}
	
	
	

	  </script>
	  
		<script>
			FB.init({
			appId:'<?php echo APP_ID ?>',
			cookie:true,
			status:true,
			xfbml:true
			});

			function FacebookInviteFriends()
			{
			FB.ui({
			method: 'apprequests',
			data: '<?php echo $link_post_face ?>',
			message: 'Your Message diaolog'
			});
			}
		</script>




