<?php
	$daugia = App_Models_DaugiaModel::getInstance();
	$UserFB = $daugia->GetInfoUserFacebook();
	//print_r($UserFB); exit;
	$SessionIdUser = $daugia->KiemTraSessionIdUser();
	if($SessionIdUser > 0)
	{
		$hoten = $daugia->GetInfoUserByIdUser($SessionIdUser);
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
       <link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/css/style.css'; ?>"></link>
       <link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/css/countdown.css'; ?>"></link>
	   
		<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/jquery-1.8.0.min.js'; ?>"></script>
		<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/script.js'; ?>"></script>
		<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/jquery.countdown.js'; ?>"></script>
		<script>
			var taaa = {};
			taaa.appdomain = "<?php echo APP_DOMAIN ?>";
			taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
		</script>
		<script>
			$(function(){
			  center()//gọi hàm mới load web
				$(window).resize(function(){center()})//gọi hàm khi resize
				//alert($(window).width());
				//alert($('#thongbao').width());
			  function center(){
				$('#thongbao').css({left:($(window).width()-$('#thongbao').width())/2,top:100});
				$('#formlogin').css({left:($(window).width()-$('#formlogin').width())/2,top:100});
			  }
			})
	  </script>
	</head>

    <body>
	<input type="hidden" id="IdUserFB" value="<?php echo $UserFB["id"];?>"/>
	<input type="hidden" id="NameUserFB" value="<?php echo $UserFB["name"];?>"/>
	<input type="hidden" id="LinkFB" value="<?php echo $UserFB["link"];?>"/>
	<div id="bg_thongbao"></div>
	<div id="thongbao">
		<!--
		<p class='title_tb'>Đổi Mật Khẩu</p><div class='content_tb'><table class='login'><tr><td width='145'>Mật khẩu cũ</td><td><input class='inputstyle' type='text' id='oldpass' name='oldpass' /></td></tr><tr><td>Mật khẩu mới</td><td><input class='inputstyle' type='text' id='newpass' name='newpass'/></td></tr><tr><td>Nhập lại mật khẩu mới</td><td><input class='inputstyle' type='text' id='newrepass' name='newrepass'/></td></tr><tr><td></td><td><input class='inputstyle2' type='button' name='btnlogin' value='Đổi mật khẩu' onclick = "ThayDoiMK(document.getElementById('oldpass').value, document.getElementById('newpass').value, document.getElementById('newrepass').value)" /></td></tr><tr><td colspan='2'><span class='loidoimk'></span></td></tr></table></div>
	-->
	
	</div>
	<div id="formlogin"></div>
	
	<div id="container">
<div id="banner">
	<div id="logo">
		<img src="<?php echo APP_DOMAIN . '/application/layouts/tmpdaugia/images/banner.jpg'?>" alt="banner" title="banner"/>
		
	</div><!--End #logo-->
</div><!--End #banner-->
<div id="main">
	<ul class="menu">
		<li><a href="home">Trang chủ</a></li>
		<li><a href="daugiasapdienra">ĐG sắp diển ra</a></li>
		<li><a href="daugiaketthuc">ĐG kết thúc</a></li>
        <li><a href="gioithieu">Giới Thiệu</a></li>
		<li><a href="dieule">Điều Lệ</a></li>
		<li><a href="lienhe">Liên Hệ</a></li>
		<li class="username">
		<?php 
			if($SessionIdUser != 0)
				echo "<a href='javascript:;'>$hoten</a><ul><li><a class='menuquenmk' href='javascript:;'>Đổi Mật Khẩu</a></li><li><a class='menudangxuat' href='javascript:;'>Đăng Xuất</a></li></ul>";
			else
				echo "<a class='menudangnhap' href='javascript:;'>Đăng Nhập</a>";
		?>	
		</li>
	</ul>
</div><!--End #main-->
<div id="content">
	<?php echo $this->layout()->content; ?>
</div><!--End #content-->
<div id="footer">
    <table width="100%">
        <tr class="tr1">
            <td colspan="3" class="tr1">Công ty TNHH Thương mại dịch vụ Tam Tài Nhân</td>
        </tr>
        <tr class="tr2">
            <td align="center">
            Chi nhánh TSN:<br />
            365 Tân Sơn Nhì, P.Tân Thành, Q.Tân Phú<br />
            Điện thoại: 08 66 743 325 – 0983 410 436
            </td>
            <td align="center">
            Chi nhánh Quận 8:<br />
            165 Dương Bá Trạc, P1, Q8, Tp.HCM<br />
            Điện thoại: 08 66 846 325 – 0986 370 325
            </td>
            <td align="center">
            Chi nhánh Bình Thạnh:<br />
            371 Bạch Đằng ,P.15 ,Q Bình Thạnh ,TPHCM<br />
            Điện thoại: 08 66 765 325 - 0919 370 325
            </td>
        </tr>
        <tr>
            <td class="copy" colspan="3" align="center">
            Copyright © 2013 www.thegioinem.com -- Xây dựng và phát triển: ISHALI MEDIA
            </td>
        </tr>
        <tr class="tr3">
            <td colspan="3" align="center"></td>
        </tr>
    </table>
</div><!--End #footer-->
</div><!--End #container-->
        
    </body>
</html>