<?php
	$daugia = App_Models_DaugiaModel::getInstance();
	$IdUserFB = $daugia->GetIdUserFB();
	$SessionIdUser = $daugia->KiemTraSessionIdUser();
	if($SessionIdUser > 0)
	{
		$hoten = $daugia->GetInfoUserByIdUser($SessionIdUser);
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
       <link type="text/css" rel="stylesheet" href="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/css/style.css'; ?>"></link>
		<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/jquery-1.8.0.min.js'; ?>"></script>
		<script type="text/javascript" src="<?php echo APP_DOMAIN . '/application/layouts/' . $this->page->templates . '/js/script.js'; ?>"></script>
    </head>

    <body>
	<input type="hidden" id="IdUserFB" value="<?php echo $IdUserFB;?>"/>
	<div id="bg_thongbao"></div>
	<div id="thongbao"></div>
	<div id="formlogin"></div>
	
	<div id="container">
<div id="banner">
	<div id="logo">
		<img src="<?php echo APP_DOMAIN . '/application/layouts/tmpdaugia/images/banner.jpg'?>" alt="banner" title="banner"/>
		
	</div><!--End #logo-->
</div><!--End #banner-->
<div id="main">
	<ul class="menu">
		<li><a href="home">Trang chủ</a></li>
		<li><a href="product">ĐG Nệm</a></li>
		<li><a href="">ĐG Chăn/Drap</a></li>
		<li><a href="">Điều Lệ</a></li>
		<li><a href="">Liên Hệ</a></li>
		<li class="username">
		<?php 
			if($SessionIdUser != 0)
				echo "<a href='javascript:;'>$hoten</a><ul><li><a class='menudangxuat' href='javascript:;'>Đăng Xuất</a></li></ul>";
			else
				echo "<a class='menudangnhap' href='javascript:;'>Đăng Nhập</a>";
		?>	
		</li>
	</ul>
</div><!--End #main-->
<div id="content">
	<?php echo $this->layout()->content; ?>
</div><!--End #content-->
<div id="footer"></div><!--End #footer-->
</div><!--End #container-->
        
    </body>
</html>