<?php
    $Lienhe = $this->lienhe;
?>

<form action = "lienhe/chinhsualienhe" method = "post" enctype="multipart/form-data">

    <textarea id="cklienhe" class="textareastyle" type="text" name="lienhe"><?php echo $Lienhe; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>
	
	var editor1 = CKEDITOR.replace( 'cklienhe' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;

</script>














