<?php
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center><img  src='".APP_DOMAIN."/application/templates/giaodien_admin/images/chon page.jpg'/></center>";
	}
	else
	{
    $Lienhe = $this->lienhe;
?>

<form action = "lienhe/chinhsualienhe" method = "post" enctype="multipart/form-data">

    <textarea id="cklienhe" class="textareastyle" type="text" name="lienhe"><?php echo $Lienhe; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>
	var editor1 = CKEDITOR.replace( 'cklienhe' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;
</script>
<?php } ?>














