<?php
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center><img  src='".APP_DOMAIN."/application/templates/giaodien_admin/images/chon page.jpg'/></center>";
	}
	else
	{
    $Gioithieu = $this->gioithieu;
?>

<form action = "gioithieu/chinhsuagioithieu" method = "post" enctype="multipart/form-data">

    <textarea id="ckgioithieu" class="textareastyle" type="text" name="gioithieu"><?php echo $Gioithieu; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>
	var editor1 = CKEDITOR.replace( 'ckgioithieu' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;
</script>

<?php } ?>














