<?php
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center><img  src='".APP_DOMAIN."/application/templates/giaodien_admin/images/chon page.jpg'/></center>";
	}
	else
	{
    $ThongBao = $this->thongbao;
?>

<form action = "thongbao/chinhsuathongbao" method = "post" enctype="multipart/form-data">

    <textarea id="ckthongbao" class="textareastyle" type="text" name="thongbao"><?php echo $ThongBao; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>
	var editor1 = CKEDITOR.replace( 'ckthongbao' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;
</script>

<?php } ?>














