<div class="form_view">
    <p style="color: #800000;font-weight: bold;"><?php echo $this->message; ?></p>
    <form method="post" action="<?php echo APP_DOMAIN; ?>/manage/config">
        <p>
            <span>Tên trang : </span>
            <input type="text" name="page_name" value="<?php echo $this->pageItem->page_name; ?>"/> 
        </p>
        <p>
            <span>Banner : </span>
            <input type="text" name="banner" value="<?php echo $this->pageItem->banner; ?>"/> 
        </p>
        <p>
            <span>Banner link : </span>
            <input type="text" name="banner_link" value="<?php echo $this->pageItem->banner_link; ?>"/> 
        </p>
        <p>
            <span>Template : </span>
            <select name="tmpl" id="tmpl">
                <option value="tmpl1">Giao diện 1</option>                
            </select> 
        </p>
        <p>
            <span>Giới tính : </span>
            <select name="show_gioi_tinh" id="show_gioi_tinh">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select> 
        </p>
        <p>
            <span>Mã : </span>
            <select name="show_ma" id="show_ma">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select>
        </p>
        <p>
            <span>Tên : </span>
            <select name="show_ten" id="show_ten">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select>
        </p>
        <p>
            <span>Lượt xem : </span>
            <select name="show_luot_xem" id="show_luot_xem">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select>
        </p>
        <p>
            <span>Lượt bình chọn : </span>
            <select name="show_so_binh_chon" id="show_so_binh_chon">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select>
        </p>
        <p>
            <span>Giới thiệu : </span>
            <select name="show_gioi_thieu" id="show_gioi_thieu">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>
            </select> 
        </p>
        <p>
            <span>Số lần bình chọn : </span>
            <select name="so_lan_binh_chon" id="so_lan_binh_chon">
                <option value="0">Một người</option>
                <option value="1">Nhiều người</option>
            </select>
        </p>
        <p>
            <span>Like bình chọn : </span>
            <select name="like_binh_chon" id="like_binh_chon">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>  
            </select> 
        </p>
        <p>
            <span>Like tham gia : </span>
            <select name="like_tham_gia" id="like_tham_gia">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>  
            </select>  
        </p>
        <p>
            <span>Like comment : </span>
            <select name="like_comment" id="like_comment">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>  
            </select> 
        </p>

        <p>
            <span>Trạng thái : </span>
            <select name="an_hien" id="an_hien">
                <option value="0">Ẩn</option>
                <option value="1">Hiển thị</option>  
            </select> 
        </p>

        <p>
            <span>Cảm ơn bình chọn : </span>
            <textarea name="cam_on_binh_chon"><?php echo $this->pageItem->cam_on_binh_chon; ?></textarea>
        </p>

        <p>
            <span>Cảm ơn tham gia : </span>
            <textarea name="cam_on_tham_gia"><?php echo $this->pageItem->cam_on_binh_chon; ?></textarea>
        </p>

        <p>
            <span>Footer : </span>
            <textarea name="footer"><?php echo $this->pageItem->footer; ?></textarea>
        </p>

        <p>
            <span>Font size : </span>
            <input type="text" name="font_size" value="<?php echo $this->pageItem->font_size; ?>"/>
        </p>

        <p>
            <span>Background color : </span>
            <input type="text" name="background_color" value="<?php echo $this->pageItem->background_color; ?>"/>
        </p>

        <p>
            <span>Background image : </span>
            <input type="text" name="background_images" value="<?php echo $this->pageItem->background_images; ?>"/>
        </p>

        <p>
            <span>Color : </span>
            <select name="color" id="color">
                <option value="#000">#000000</option>
            </select>
        </p>

        <p>
            <input type="submit" value="Cập nhật"/>
        </p>
    </form>
</div>

<script>
    common.selectOptionByValue('tmpl', '<?php echo $this->pageItem->templates; ?>');
    common.selectOptionByValue('show_gioi_tinh', '<?php echo $this->pageItem->show_gioi_tinh; ?>');
    common.selectOptionByValue('show_ma', '<?php echo $this->pageItem->show_ma; ?>');
    common.selectOptionByValue('show_ten', '<?php echo $this->pageItem->show_ten; ?>');
    common.selectOptionByValue('show_luot_xem', '<?php echo $this->pageItem->show_luot_xem; ?>');
    common.selectOptionByValue('show_so_binh_chon', '<?php echo $this->pageItem->show_so_binh_chon; ?>');
    common.selectOptionByValue('show_gioi_thieu', '<?php echo $this->pageItem->show_gioi_thieu; ?>');
    common.selectOptionByValue('so_lan_binh_chon', '<?php echo $this->pageItem->so_lan_binh_chon; ?>');
    common.selectOptionByValue('like_binh_chon', '<?php echo $this->pageItem->like_binh_chon; ?>');
    common.selectOptionByValue('like_tham_gia', '<?php echo $this->pageItem->like_tham_gia; ?>');
    common.selectOptionByValue('like_comment', '<?php echo $this->pageItem->like_comment; ?>');
    common.selectOptionByValue('an_hien', '<?php echo $this->pageItem->an_hien; ?>');
    common.selectOptionByValue('color', '<?php echo $this->pageItem->color; ?>');    
</script>
