<?php
    $ThongBao = $this->thongbao;
?>

<form action = "thongbao/chinhsuathongbao" method = "post" enctype="multipart/form-data">

    <textarea id="ckthongbao" class="textareastyle" type="text" name="thongbao"><?php echo $ThongBao; ?></textarea>
	
    <input type="submit" name="btnsubmit" value="Chỉnh Sửa"/>

</form>

<script>
	
	var editor1 = CKEDITOR.replace( 'ckthongbao' );
	CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;

</script>














